[
    { "id": "a", "title": "ROOM A" },
    { "id": "b", "title": "ROOM B" },
    { "id": "c", "title": "ROOM C" },
    { "id": "d", "title": "ROOM D" },
    { "id": "e", "title": "ROOM E" },
    { "id": "f", "title": "ROOM F" },
    { "id": "g", "title": "ROOM G" },
    { "id": "h", "title": "ROOM H" },
    { "id": "i", "title": "ROOM I" },
    { "id": "j", "title": "ROOM J" },
    { "id": "k", "title": "ROOM K" },
    { "id": "l", "title": "ROOM L" },
    { "id": "m", "title": "ROOM M" },
    { "id": "n", "title": "ROOM N" },
    { "id": "o", "title": "ROOM O" },
    { "id": "p", "title": "ROOM P" },
    { "id": "q", "title": "ROOM Q" },
    { "id": "r", "title": "ROOM R" },
    { "id": "s", "title": "ROOM S" },
    { "id": "t", "title": "ROOM T" },
    { "id": "u", "title": "ROOM U" },
    { "id": "v", "title": "ROOM V" },
    { "id": "w", "title": "ROOM W" },
    { "id": "x", "title": "ROOM X" },
    { "id": "y", "title": "ROOM Y" },
    { "id": "z", "title": "ROOM Z" }
]